### ISSUE TITLE
избавиться от #!/

### ISSUE THREAD

**Issue by bmsdave** [birdy90/ND6-Diploma#1]
Это можно сделать через
`$locationProvider.html5Mode(true)`
см. https://docs.angularjs.org/guide/$location

но нужно понимать, что сервер тоже нужно настроить так что бы он всегда отдавал наше SPA-приложение и на запросы типа: `http://gob.servebeer.com:8000/list` и на `http://gob.servebeer.com:8000/kitchen`

**Comment by birdy90** [comment]
206973eea52d3c0fe28b3b0a1d23df98bad23220 
переделаны ссылки для приложений, в том числе добавлена обработка 404й страницы
