### ISSUE TITLE
причесать package.json

### ISSUE THREAD

**Issue by bmsdave** [birdy90/ND6-Diploma#2]
1. `dependencies` разделить на `dependencies` и `devDependencies`
2. сделать скрипты для управлением приложения. например `npm start` по которому запустится сервер.

**Comment by birdy90** [comment]
138ecab2a4ca18b63c9c638f93390da2dbf2b80f
сделал только одну команду `start`, а в `devDependencies` добавил модули, используемые для тестирования

**Comment by bmsdave** [comment]
Хорошо!
