### ISSUE TITLE
следовать angular style guide

### ISSUE THREAD

**Issue by bmsdave** [birdy90/ND6-Diploma#3]
ознакомиться с https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md
и привести приложение в соответствующий стиль.

**Comment by birdy90** [comment]
5d163e385edce1a07447a13b1112c392105110c5
сделал рефакторинг. опирался не только на стайлгайд, но и временами на здравый смысл. некоторые вещи в стайлгайде не очень понял, поэтому, возможно, что-то не доделал

**Comment by bmsdave** [comment]
Отлично! за использование controller вместо scope отдельное спасибо!
Этот момент очень важен при переходе с angularjs на angular.
