### ISSUE TITLE
Протестировать сервисы

### ISSUE THREAD

**Issue by bmsdave** [birdy90/ND6-Diploma#4]
Добавить unit-тесты

Считается хорошим стилям, файлы тестов разполагать рядом с исходным кодом который они тестируют. Поэтому прошу сделать подобную структуру в `ND6-Diploma/src/services/`:
```
auth.js
auth.spec.js
filters.js
filters.spec.js
orders.js
orders.spec.js
```

И в каждом spec файле протистировать пару основных методов сервиса ( все не нужно ).
Важно попробовать написать тесты на примере указанных здесь:
https://docs.angularjs.org/guide/services

понять как работать mock'ами. Как их создавать, как их подкладывать вместо настоящих данных и структур.

**Comment by birdy90** [comment]
Честно сказать, оказался в некотором ступоре от ошибки `module is not a function`. Очевидно, её нужно включить. Но тестируется ангуляр, значит, на клиенте, значит, наверное, и тесты тоже надо гонять как-то на клиенте. И тут меня накрывает, потому что запускать тесты на клиенте не кажется хорошей затеей

**Comment by birdy90** [comment]
А не, кажется понял. Сейчас пробую запустить всё через `karma`

**Comment by birdy90** [comment]
95df222f2f3613d842cd3605b4bd40a1f56e6500
Возник вопрос. Как я понял из примера, `mock` используется для подмены какого-то поведения. В примере заменялся `alert`. Я подумал, что могу, для примера, заменить вызов `$resource.get`. 

https://github.com/birdy90/ND6-Diploma/blob/master/src/services/auth.spec.js
В файле я попробовал создать "шпиона" с помощью `chai`, он вроде бы создался, но он не заменил собой нужный мне метод. То есть, тест выполняется, но не проходит (первый тест должен быть проваленным, потому что там нет такого вызова, а второй должен быть пройден). у меня же проваливаются оба с сообщением `expected { Spy } to have been called`. Пример работы с `chai-spies` брал тут: https://github.com/chaijs/chai-spies. 

Если я пробую сделать что-то наподобие
```javascript
module(function($provide) {
  $provide.value('$window', mock);
});
```
то не очень понятно, чем мне заменить $window. То есть, в какой-то момент я попробовал поставить туда `$provide.value(service.userResource, mock);`, но столкнулся с проблемой:
- inject вызывается позже, и service получается неопределенным

Попробовал своё предположение из последнего абзаца переписать с кавычками, файл получился таким:

```javascript
describe('auth service testing', () => {
  let service;
  let mock = {get: chai.spy()};

  beforeEach(module('app'));
  beforeEach(() => {
    module(function($provide) {
      $provide.value('service.userResource', mock);
    });

    inject($injector => {
      service = $injector.get('UserService');
    });
  });

  it('should return a user', () => {
    const user = service.user();
    expect(user).to.have.own.property('name');
    expect(user).to.have.own.property('email');
    expect(user).to.have.own.property('money');

    expect(mock.get).to.have.been.called();
  });

  it('should use user resource', () => {
    service.getUser();

    expect(mock.get).to.have.been.called();
  });
  
  ...
});
```
Тесты хотя бы выполнились. Но результат остался прежним: `expected { Spy } to have been called`. Я явно упускаю что-то, и, кажется, что упущенное мной не так уж и сложно

**Comment by bmsdave** [comment]
1. в karma.conf.js стоит добавить плагины:
```
config.set({
 ###
    plugins : [
      require('karma-mocha'),
      require("karma-chai-spies"),
      require("karma-chai"),
      require("karma-chrome-launcher")
    ],
 ###
```

честно говоря, удивлен что работает без этого аттрибута)

**Comment by bmsdave** [comment]
2. Вот пример теста который успешно пройдет и где spy отработает:
auth.spec.js
```
describe('auth service testing', () => {
  let service;
  let spies = {};

  beforeEach(module('app'));
  beforeEach(() => {
    inject($injector => {
      service = $injector.get('UserService');
      spies.test = chai.spy.on(service, 'test');
    });
  });

  it('should use user resource', () => {
    service.getUser({email:"test"});

    expect(spies.test).to.have.been.called();
  });

});
```

auth.js
```
(() => {
  'use strict';

  angular.module('app')
    .service('UserService', UserService);

  function UserService($resource) {
    this.emptyUser = {
      name: '',
      email: '',
      money: 0,
    };

    let userInstance = this.emptyUser;

    this.userResource = $resource('/api/user/:email', {email: '@email'});
    this.moneyResource = $resource('/api/money/:email', {email: '@email'});

    this.user = () => userInstance;
    this.test = () => console.log("test");
    
    this.getUser = data => new Promise((done, fail) => {
      this.test();
      this.userResource.get({email: data.email}, resourceData => {
        if (resourceData.answer.length === 0) {
          data.money = 100;
          this.userResource.save({user: data});
          resourceData = data;
        } else {
          resourceData = resourceData.answer[0];
        }
        userInstance = resourceData;
        userInstance.name = data.name;
        done(userInstance);
      });
    });

    this.getMoney = () => new Promise((done, fail) => {
      this.moneyResource.get({email: userInstance.email}, data => done(data.answer[0].money));
    });

    this.setMoney = amount => new Promise((done, fail) => {
      userInstance.money = amount;
      this.moneyResource.save({email: userInstance.email, money: amount}, data => done(data.answer[0].money));
    });

    this.buy = cost => {
      userInstance.money -= cost;
    }
  }
})();
```

**Comment by bmsdave** [comment]
Первоначально нужно исправить проблему с тем, что в `service.getUser();` вызыдается с пустыми аргуметами. Отсюда получается  `Cannot read property 'email' of undefined`

3. чтобы протестировать методы $resource, здесь нужен объект $httpBackend.
Пример можно найти здесь:
https://stackoverflow.com/questions/18258490/testing-resource-services-in-angularjs
https://medium.com/testing-angular/testing-an-angular-resource-factory-59c5491ec3a6

**Comment by birdy90** [comment]
Как я понял происходящее:
1. работает потому, что браузер добавлен в поле `browsers`, а плагины - в поле `frameworks`
2. действительно, так отработало. То есть, мы создаем некоторый метод, который нужно в логике вызывать, и, фактически, самое полезное, что можно извлечь - количество вызовов. А это, в какой-то момент, показалось бесполезной затеей. К слову, моки используются для подобной подмены методов? То, что мы сделали со шпионами - это и есть моки?
3. воспользовался бэкендом. Как я понял - он просто подменяет на один раз настоящий сервер, так чтобы апи не требовалось поднимать перед запуском (или, в случае TDD, чтобы можно было использовать апи до его написания)

**Comment by birdy90** [comment]
Собственно, протестировал полностью сервис `Auth`, фильтры, оказалось, делаются чуть-чуть по-другому, а сервис `Orders` тестировать полностью не стал, так как там почти всюду просто вызов одного метода апи, поэтому взял метод, в котором есть "вариации" и потестил его

**Comment by bmsdave** [comment]
Прошу прощение за задержку с ответом.

> К слову, моки используются для подобной подмены методов?

Да. так и есть.

> То, что мы сделали со шпионами - это и есть моки?

Нет. Шпионы следят за тем был ли вызван какой-либо метод. Причем шпионы могут и не знать что метод замокан или же не замокан.

> воспользовался бэкендом. Как я понял - он просто подменяет на один раз настоящий сервер, так чтобы апи не требовалось поднимать перед запуском (или, в случае TDD, чтобы можно было использовать апи до его написания)

Да, все верно. Это грубо говоря мок для апи и/или ресурсов сервера.

**Comment by bmsdave** [comment]
По тестирования больше замечаний нет. Спасибо за работу!
